game_time: 100
robot_time: 25
log_level: 'DEBUG'

charging_time: 5
charging_amount: 25

points:
  good: 2
  wrong: -1
  bad: -3

fields_names:
  - game_field
  - blue_plastic # blue
  - blue_glass # green
  - red_plastic # red
  - red_glass # black

objects:
  plastic: # red
    - 30
    - 32
    - 41
    - 35
  glass: # green
    - 47
    - 36
    - 43
    - 22
  shells: # blue
    - 29
    - 40
    - 39
    - 18

robots:
  0:  Ocvrte antenice
  5:  GaSa Dynamics
  9:  Works on Our Machine 
  10: Leščurji
  12: los programadores
  14: Unicode Abuse
  19: Ibržnik
  24: Red
  27: Blue
  25: Demo

